### ISSUE TITLE
[Bug]unable to locate package tool-x

### ISSUE THREAD

**Issue by nisargranipa** [ekadanuarta/Tool-X#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mund420** [comment]
Android vivo 1802
Versi 8.1.0

**Comment by Mund420** [comment]
![Uploading Screenshot_2022_1011_081034.jpg…]()
