### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by voidlen** [ekadanuarta/Tool-X#10]
**Describe the bug**
will not connect to the internet to 

**To Reproduce**
1. Go to 'any of the installers'
2. Click on 'the installer'

**Expected behavior**
will give an error that there is no network connection

**Screenshots**
![Screenshot 2023-03-31 2 49 12 PM](https://user-images.githubusercontent.com/125597058/229204919-ed34035c-d1fe-472e-a2b8-356c3d82d2aa.png)
]

**Smartphone (please complete the following information):**
 - Device: [chromebook]
 - OS: [debian]
 - Version [11

**Additional context**

**Comment by ekadanuarta** [comment]
okey
