### ISSUE TITLE
tool not installated

### ISSUE THREAD

**Issue by daniloGamer11** [ekadanuarta/Tool-X#4]
appears "the tool (example) is not installed,
![Screenshot_20221210-232654](https://user-images.githubusercontent.com/116130188/206883581-a721db09-e0c0-46ca-ae3f-316c6971e471.png)

 I literally download toolX to install and use a tool that I did not download

**Comment by daniloGamer11** [comment]
the same thing on pc

**Comment by dvrk47** [comment]
same here

**Comment by TheNewsYorkTime** [comment]
Same

**Comment by ekadanuarta** [comment]
Maaf karena tools ini sudah lama
