### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jood112** [ekadanuarta/Tool-X#7]
**Describe the bug**
When i try to install packages it says that there is no network connection but i  am connected to internet
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jood112** [comment]
When i try to install packages it says that there is no network connection but i am connected to internet

**Comment by voidlen** [comment]
Same problem here!

**Comment by ekadanuarta** [comment]
Karena tools ini sudah lama dan sudah banyak perubahan pada bahasa pemrograman
