### ISSUE TITLE
git clone https://github.com/rajkumardusad/tool-x.git/ Cloning into 'tool-x'... Username for 'https://github.com': Password for 'https://github.com': remote: Repository not found. fatal: Authentication failed for 'https://github.com/rajkumardusad/tool-x.git/'

### ISSUE THREAD

**Issue by omkartiru** [ekadanuarta/Tool-X#8]
**Describe the bug**
git clone https://github.com/rajkumardusad/tool-x.git/
Cloning into 'tool-x'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/rajkumardusad/tool-x.git/'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by omkartiru** [comment]
git clone https://github.com/rajkumardusad/tool-x.git/
Cloning into 'tool-x'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/rajkumardusad/tool-x.git/'

**Comment by omkartiru** [comment]
![Uploading Screenshot_20230323-225724_Termux.jpg…]()

**Comment by ekadanuarta** [comment]
Tools ini sudah lama

**Comment by LegnaNesir** [comment]
Tf does that mean. That doesn't explain shit asshole.
