### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by omkartiru** [ekadanuarta/Tool-X#9]
**Describe the bug**
git clone https://github.com/ekadanuarta/Tool-X
fatal: destination path 'Tool-X' already exists and is not an empty directory.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ekadanuarta** [comment]
Karena saya sedang sibuk mengurus keluarga jadi tools ini tidak saya lanjutkan
